#services:
#    theapi_bathroom_scales.example:
#        class: Theapi\BathroomScalesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    theapi_bathroom_scales:
        people_json: '[["Him",80,150],["Her",30,79]]'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Theapi\BathroomScalesBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Theapi\BathroomScalesBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    Theapi\BathroomScalesBundle\Service\WeightProcessor:
        public: true
        tags:
            - { name: event_subscriber }
        calls:
            - method: setContainer
              arguments:
                  - '@service_container'

    Theapi\BathroomScalesBundle\Service\People\PeopleService:
        public: true
        calls:
            - method: setJson
              arguments:
                  - '%theapi_bathroom_scales.people_json%'